//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLTodayLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class QDEPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QDEPT()
        {
            this.QDELs = new HashSet<QDEL>();
            this.QEMPs = new HashSet<QEMP>();
            this.QSALEs = new HashSet<QSALE>();
        }
    
        public string DEPTNAME { get; set; }
        public int DEPTFLOOR { get; set; }
        public int DEPTPHONE { get; set; }
        public int EMPNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QDEL> QDELs { get; set; }
        public virtual QEMP QEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QEMP> QEMPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QSALE> QSALEs { get; set; }
    }
}
